### ISSUE TITLE
Generic sub-model schema definition not found

### ISSUE THREAD

**Issue by shixinla** [sanic-org/sanic-ext#144] opened 2022-10-11 12:40 UTC
**Describe the bug**
- Geting `Could not resolve reference: Could not resolve pointer: /definitions/Test does not exist in document` error in swagger
- versions
```
pydantic==1.10.2
sanic==22.9.0
sanic_ext==22.9.0
```

**Screenshots**
error:
![image](https://user-images.githubusercontent.com/84222913/195091113-a13681c1-f2a2-4369-8c1a-fbe9ddd4a933.png)

no sub-model schema:
![image](https://user-images.githubusercontent.com/84222913/195091337-a15c1795-0462-462f-a616-d2c5c1d4ef91.png)

**To Reproduce**

my models.py
```python
from datetime import date
from pydantic import BaseModel, Field
from pydantic.generics import GenericModel
from typing import Generic, TypeVar, Optional

T = TypeVar('T')


class RespModel(GenericModel, Generic[T]):
    code: int = Field(description="business code", example=0, default=0)
    data: T = Field(description="business data")
    msg: str = Field(description="msg", example="success", default="success")


class Test(BaseModel):
    foo: str = Field(description="Foo Description", example="FOOO")
    bar: str = "test"

```

```python
@openapi.definition(
    summary="Test post api",
    parameter=[
        # query
        Parameter(name="test", schema=str, location="query"),
        # cookie
        Parameter(name="cookie", schema=str, location="cookie"),
        # header parameter
        Parameter(name="token", schema=str, location="header")
    ],
    body=RequestBody(
        {'application/json': Test.schema()}, required=True
    ),
    response=[
        Response(
            {'application/json': RespModel[Test].schema()},
            description="success",
            status=200
        )
    ],
)
```

**Additional context**
If I am using the wrong method, please point it out, thank you

**Comment by ahopkins** [comment] 2022-10-20 06:33
This is not a bug.

I think you need to do two things:

1. Add `Test` as a component:

```python
openapi.component(Test)
```

2. Built the `RespModel` with the correct ref template:

```python
    response=[
        Response(
            {
                "application/json": RespModel[Test].schema(
                    ref_template="#/components/schemas/{model}"
                )
            },
            description="success",
            status=200,
        )
    ],
```

**Comment by ahopkins** [comment] 2022-10-20 06:37
Looking at it closer, I think there is an even better solution since Pydantic is including `Test` inside the `RespModel` spec.


```python
    response=[
        Response(
            {
                "application/json": RespModel[Test].schema(
                    ref_template="#5/definitions/{model}"
                )
            },
            description="success",
            status=200,
        )
    ],
```

**Comment by pahrohfit** [comment] 2022-12-05 20:32
What/where is this `#5` coming from?

**Comment by ahopkins** [comment] 2022-12-05 21:24
What is the question?

**Comment by pahrohfit** [comment] 2022-12-05 21:42
> What is the question?

In your last response, you have a `ref_template` value that begins with "#5" ... what is that "5", how is it resolving to anything valid?

**Comment by ahopkins** [comment] 2022-12-20 21:09
> In your last response, you have a `ref_template` value that begins with "#5" ... what is that "5", how is it resolving to anything valid?

Its not. Was a typo. :man_facepalming:

**Closed** 2022-12-20 21:10 UTC
