### ISSUE TITLE
`openapi.Parameter` location is ignored when defined from the `openapi.definition` decorator

### ISSUE THREAD

**Issue by prryplatypus** [sanic-org/sanic-ext#11] opened 2021-11-29 11:06 UTC
**Describe the bug**
When a parameter has a defined location such as "path" or "header" and is defined using the `openapi.definition` decorator, the location seems to be ignored and is shown as "query".

**Screenshots**
![SwaggerUI example](https://user-images.githubusercontent.com/25409753/143856832-f7c0541e-d398-4717-ba53-5e6ef95f864c.png)

**To Reproduce**
Use the decorator like so:
```python
@openapi.definition(
    parameter=[
        openapi.Parameter("enterprise", str, "path"),
    ],
)
```

**Expected behavior**
The parameter is marked as whatever type it's set to, and isn't overriden by the fallback value.

**Environment (please complete the following information):**
 - Version 21.9.1

**Comment by ChihweiLHBird** [comment] 2021-12-22 03:50
`body` seems not in the possible values of the `in` field in openapi's docs:
https://spec.openapis.org/oas/latest.html#fixed-fields-9

For the request body, https://spec.openapis.org/oas/latest.html#request-body-examples

**Comment by ahopkins** [comment] 2021-12-22 05:41
Not a bug as @ChihweiLHBird stated. You need to use the `body` kwarg.

**Comment by prryplatypus** [comment] 2021-12-22 08:35
This isn't just for `body`. It happens with `path` and `header` too, which **are** possible values for the `in` field in OpenApi's docs. I've updated the original issue to reflect it with valid parameters.

This doesn't work:
```py
@openapi.definition(
    parameter=[
        openapi.Parameter("enterprise", str, location="path"),
    ],
)
```

This does:
```py
@openapi.parameter("enterprise", str, location="path")
```

**Comment by ChihweiLHBird** [comment] 2021-12-22 09:08
> This isn't just for `body`. It happens with `path` and `header` too, which **are** possible values for the `in` field in OpenApi's docs. I've updated the original issue to reflect it with valid parameters.
> 
> This doesn't work:
> 
> ```python
> @openapi.definition(
>     parameter=[
>         openapi.Parameter("enterprise", str, location="path"),
>     ],
> )
> ```
> 
> This does:
> 
> ```python
> @openapi.parameter("enterprise", str, location="path")
> ```

Yes, you are right. A pull request was created for this issue. Thank you!

**Comment by prryplatypus** [comment] 2021-12-22 09:16
Haha, thank u! :)

**Comment by ChihweiLHBird** [comment] 2021-12-23 05:30
Should has been fixed in https://github.com/sanic-org/sanic-ext/pull/27, closing the issue.
Thank you, @prryplatypus

**Closed by ChihweiLHBird** 2021-12-23 05:30 UTC
Labels: bug
