### ISSUE TITLE
[Bug] Not correct openapi json for ReDoc with dynamically generated classes

### ISSUE THREAD

**Issue by charoduke** [sanic-org/sanic-ext#74] opened 2022-04-27 07:27 UTC
Hello. I make class views dynamically from SA models for REST api.  And in ReDoc all summary for methods like last class.

![bug_2022-04-27_10-18-48](https://user-images.githubusercontent.com/52139414/165463440-5a68bbec-7c50-4504-b8f6-fadc2cda8f0c.png)

Class view generate like this:
```
....................
views.append(type(f"VI_{name}",
                               (HTTPMethodView,),
                               {'model': model, 
                               '_url': f'/{name}/<id:int>',
                               'get': op.summary(f"Get obj {name}")(viewItem_get),
                               'put': op.summary(f"Update obj {name}")(viewItem_put),
                               'patch': op.summary(f"Change obj {name}")(viewItem_patch),
                               'delete': op.summary(f"Delete obj {name}")(viewItem_delete)}))

......................... 
for view in views:
    blueprint.add_route(view.as_view(), view._url)
```

I find way to generate custom summary and all openapi  fields for every my dynamic class-view.

I use Manjaro + firefox. Sanic v22.3.1 and sanic-ext==22.3.1

I try deepcopy, copy all objects and copy func-methods for set unique names for every gen but  it not help all.

**Comment by ahopkins** [comment] 2022-05-24 05:53
I guess I am not sure what the problem is. What would the expected outcome be?

**Comment by charoduke** [comment] 2022-05-28 09:23
> I guess I am not sure what the problem is. What would the expected outcome be?



I'm trying just use template  op.summary(f"Get obj {name}") with list of names.

in https://github.com/sanic-org/sanic-ext/blob/main/sanic_ext/extensions/openapi/openapi.py   line 412-422

```
if summary:
      func = glbl["summary"](summary)(func)
```
There 'func' is key to collect data. 

But I have many dynamic view classes from same func-methods  

```
type(f"VI_{name}",
     (HTTPMethodView,),
     {get': op.summary(f"Get obj {name}")(viewItem_get),....

```
Where viewItem_get is func.

so ...
I have one last summary for all definitions in json of openapi. With last 'name' for all.

**Comment by ahopkins** [comment] 2022-05-29 12:27
I think I see what you are after here. I am not sure that we are likely to change this as it would potentially have a lot of complications for a narrow use case. Especially since I think there are a few alternatives that will get you there.

## Using `partial`

Perhaps the easiest solution is to just wrap your functions in `partial`. That creates the function as a new/unique instance.

```python
from functools import partial

from sanic import Blueprint, Sanic
from sanic.views import HTTPMethodView
from sanic_ext import openapi

app = Sanic(__name__)
bp = Blueprint("auto")
app.blueprint(bp)


def get(*_):
    ...


def put(*_):
    ...


def patch(*_):
    ...


def delete(*_):
    ...


for name in ["foo", "bar"]:
    view = type(
        f"VI_{name}",
        (HTTPMethodView,),
        {
            "_url": f"/{name}",
            "get": openapi.summary(f"get - {name}")(partial(get)),
            "put": openapi.summary(f"put - {name}")(partial(put)),
            "patch": openapi.summary(f"patch - {name}")(partial(patch)),
            "delete": openapi.summary(f"delete - {name}")(partial(delete)),
        },
    )
    bp.add_route(view.as_view(), view._url)
```

![image](https://user-images.githubusercontent.com/166269/170867609-fc8ba070-a02f-4baa-9643-94e6c09e1c79.png)

## Factory

Personally, I would (and do) opt for this approach as it is much easier to read.

```python
from sanic import Blueprint, Sanic
from sanic.views import HTTPMethodView
from sanic_ext import openapi

app = Sanic(__name__)
bp = Blueprint("auto")
app.blueprint(bp)


def create_view(name, bp):
    class CustomView(HTTPMethodView, attach=bp, uri=f"/{name}"):
        @openapi.summary(f"get - {name}")
        def get(*_):
            ...

        @openapi.summary(f"put - {name}")
        def put(*_):
            ...

        @openapi.summary(f"patch - {name}")
        def patch(*_):
            ...

        @openapi.summary(f"delete - {name}")
        def delete(*_):
            ...


for name in ["foo", "bar"]:
    create_view(name, bp)
```

If you are doing this, you probably also want to se `operation` so that each one has a unique explicit name:

```python
        @openapi.summary(f"get - {name}")
        @openapi.operation(f"get_{name}")
        def get(*_):
            ...

        @openapi.summary(f"put - {name}")
        @openapi.operation(f"put_{name}")
        def put(*_):
            ...

        @openapi.summary(f"patch - {name}")
        @openapi.operation(f"patch_{name}")
        def patch(*_):
            ...

        @openapi.summary(f"delete - {name}")
        @openapi.operation(f"delete_{name}")
        def delete(*_):
            ...
```

Or, just combine it:

```python
        @openapi.definition(
            summary=f"get - {name}",
            operation=f"get_{name}",
        )
        def get(*_):
            ...

        @openapi.definition(
            summary=f"put - {name}",
            operation=f"put_{name}",
        )
        def put(*_):
            ...

        @openapi.definition(
            summary=f"patch - {name}",
            operation=f"patch_{name}",
        )
        def patch(*_):
            ...

        @openapi.definition(
            summary=f"delete - {name}",
            operation=f"delete_{name}",
        )
        def delete(*_):
            ...
```

I am closing this as I think you can achieve what you want already. LMK if this works for you or not.

**Closed by ahopkins** 2022-05-29 12:27 UTC
